grpc:
  port: 6556
  enableReflection: true
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  application:
    name: grpc_server